[package]
name = "http-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
httpdate = "1"
mime_guess = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
